In [4]:
import pandas as pd
import numpy as np
import os
from functions.data_preprocessing import *
import pm4py

# BPI2017

In [6]:
bpi17 = pd.read_csv('OCEL/BPIC17.csv', sep=',')
with pd.option_context('display.max_columns', None): 
    display(bpi17)

,event_None,event_Unnamed: 0,event_id,application,event_activity,event_start_timestamp,event_timestamp,event_LoanGoal,event_ApplicationType,event_RequestedAmount,event_Action,event_FirstWithdrawalAmount,event_Accepted,event_NumberOfTerms,offer,event_org:resource,event_MonthlyCost,event_EventOrigin,event_EventID,event_Selected,event_CreditScore,event_OfferedAmount,event_CaseID
0,0,0,0,['Application_652823628'],Create application,2016/01/01 10:51:15.304,2016/01/01 10:51:15.304,Existing loan takeover,New credit,20000.0,Created,NaN,NaN,NaN,NaN,User_1,NaN,Application,Application_652823628,NaN,NaN,NaN,Application_652823628
1,1,1,1,['Application_652823628'],Submit,2016/01/01 10:51:15.352,2016/01/01 10:51:15.352,Existing loan takeover,New credit,20000.0,statechange,NaN,NaN,NaN,NaN,User_1,NaN,Application,ApplState_1582051990,NaN,NaN,NaN,Application_652823628
2,2,2,6,['Application_652823628'],Complete,2016/01/02 11:45:22.429,2016/01/02 11:45:22.429,Existing loan takeover,New credit,20000.0,Obtained,NaN,NaN,NaN,NaN,User_17,NaN,Workflow,Workitem_1875340971,NaN,NaN,NaN,Application_652823628
3,3,3,8,['Application_652823628'],Accept,2016/01/02 12:23:04.299,2016/01/02 12:23:04.299,Existing loan takeover,New credit,20000.0,statechange,NaN,NaN,NaN,NaN,User_52,NaN,Application,ApplState_99568828,NaN,NaN,NaN,Application_652823628
4,4,4,10,['Application_652823628'],Create offer,2016/01/02 12:29:05.354,2016/01/02 12:29:05.354,Existing loan takeover,New credit,20000.0,statechange,20000.0,True,44.0,['Offer_148581083'],User_52,498.29,Offer,OfferState_1514834199,True,979.0,20000.0,Application_652823628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393926,393926,393926,1160394,['Application_1350494635'],Create offer,2017/01/02 20:25:00.040,2017/01/02 20:25:00.040,Home improvement,New credit,20000.0,statechange,20000.0,False,77.0,['Offer_1580299144'],User_96,297.81,Offer,OfferState_30384573,False,0.0,20000.0,Application_1350494635
393927,393927,393927,1160395,NaN,Send (mail and online),2017/01/02 20:27:20.453,2017/01/02 20:27:20.453,Home improvement,New credit,20000.0,statechange,20000.0,False,77.0,['Offer_1580299144'],User_96,297.81,Offer,OfferState_1959881309,False,0.0,20000.0,Application_1350494635
393928,393928,393928,1160397,['Application_1350494635'],Call,2017/01/02 20:27:20.472,2017/01/02 20:27:20.472,Home improvement,New credit,20000.0,Obtained,20000.0,False,77.0,['Offer_1580299144'],User_96,297.81,Workflow,Workitem_358206591,False,0.0,20000.0,Application_1350494635
393929,393929,393929,1160402,['Application_1350494635'],Cancel application,2017/01/16 10:51:21.114,2017/01/16 10:51:21.114,Home improvement,New credit,20000.0,statechange,20000.0,False,77.0,['Offer_1580299144'],User_28,297.81,Application,ApplState_1869071797,False,0.0,20000.0,Application_1350494635
393930,393930,393930,1160403,['Application_1350494635'],Cancel offer,2017/01/16 10:51:21.139,2017/01/16 10:51:21.139,Home improvement,New credit,20000.0,statechange,20000.0,False,77.0,['Offer_1580299144'],User_28,297.81,Offer,OfferState_420066181,False,0.0,20000.0,Application_1350494635

In [7]:
bpi17 = bpi17.drop(columns=['event_None', 'event_Unnamed: 0', 'event_start_timestamp', 'event_EventID','event_CaseID'])
objects = ['application', 'offer']
first_cols = ['event_id', 'event_timestamp', 'event_activity'] + objects
split = []

bpi17 = preprocess_dataframe(bpi17, first_cols, split)
bpi17.describe()
directory = 'data-prepro'
filename = directory + '/bpi17_prepro.csv'

if not os.path.exists(directory):
    os.makedirs(directory)

bpi17.to_csv(filename, index=False)

# DS2

In [8]:
ds2 = pd.read_csv('OCEL/DS2.csv', sep=',')
with pd.option_context('display.max_columns', None): 
    display(ds2)
print(ds2.columns)
ds2.columns = ds2.columns.str.replace('ocel:', '')
ds2.columns = ds2.columns.str.replace('type:', '')
ds2 = ds2.rename(columns={'timestamp': 'event_timestamp', 'activity': 'event_activity'})

,event_id,ocel:timestamp,ocel:activity,weight,price,ocel:type:items,ocel:type:products,ocel:type:customers,ocel:type:orders,ocel:type:packages
0,1,2019-05-20 09:07:47,place order,3.520,524.96,"['880001', '880004', '880003', '880002']","['Echo Studio', 'Echo Show 8', 'Fire Stick 4K'...",['Marco Pegoraro'],['990001'],NaN
1,2,2019-05-20 10:35:21,place order,2.656,3255.99,"['880008', '880005', '880006', '880007']","['Kindle', 'iPad Air', 'iPad', 'MacBook Air']",['Gyunam Park'],['990002'],NaN
2,3,2019-05-20 10:38:17,pick item,0.483,79.99,['880006'],['Kindle'],['Gyunam Park'],['990002'],NaN
3,4,2019-05-20 11:13:54,confirm order,3.520,524.96,"['880001', '880004', '880003', '880002']","['Echo Studio', 'Echo Show 8', 'Fire Stick 4K'...",['Marco Pegoraro'],['990001'],NaN
4,5,2019-05-20 11:20:13,pick item,0.280,89.99,['880002'],['Fire Stick 4K'],['Marco Pegoraro'],['990001'],NaN
...,...,...,...,...,...,...,...,...,...,...
22362,22363,2020-08-18 11:11:09,send package,0.606,1275.00,"['888072', '888071']","['iPhone 11', 'iPad Air']",['Majid Rafiei'],['991976'],['661324']
22363,22364,2020-08-19 17:57:32,package delivered,0.606,1275.00,"['888072', '888071']","['iPhone 11', 'iPad Air']",['Majid Rafiei'],['991976'],['661324']
22364,22365,2020-08-22 01:00:00,create package,0.172,699.00,['888091'],['iPhone X'],['Mohammadreza Fani Sani'],['991983'],['661325']
22365,22366,2020-08-24 11:14:47,send package,0.172,699.00,['888091'],['iPhone X'],['Mohammadreza Fani Sani'],['991983'],['661325']
22366,22367,2020-08-25 16:30:41,package delivered,0.172,699.00,['888091'],['iPhone X'],['Mohammadreza Fani Sani'],['991983'],['661325']

Index(['event_id', 'ocel:timestamp', 'ocel:activity', 'weight', 'price',
       'ocel:type:items', 'ocel:type:products', 'ocel:type:customers',
       'ocel:type:orders', 'ocel:type:packages'],
      dtype='object')

In [9]:
# Apply preprocessing
objects = ['orders', 'packages', 'items'] # 对象类别对应的列名
first_cols = ['event_id', 'event_timestamp', 'event_activity'] + objects  
split = ['products', 'customers']
ds2 = preprocess_dataframe(ds2, first_cols, split)
with pd.option_context('display.max_columns', None): 
    display(ds2)

,event_id,event_timestamp,event_activity,orders,packages,items,weight,price,products_Echo_Dot,products_Echo_Plus,products_Echo_Show_5,products_Echo_Show_8,products_Echo_Studio,products_Echo,products_Fire_Stick_4K,products_Fire_Stick,products_Kindle_Paperwhite,products_Kindle,products_MacBook_Air,products_MacBook_Pro,products_iPad_Air,products_iPad_Pro,products_iPad_mini,products_iPad,products_iPhone_11_Pro,products_iPhone_11,products_iPhone_8,products_iPhone_X,customers_Anahita_Farhang_Ghahfarokhi,customers_Christina_Rensinghof,customers_Christine_Dobbert,customers_Claudia_Graf,customers_Gyunam_Park,customers_Junxiong_Gao,customers_Kefang_Ding,customers_Lisa_Mannel,customers_Luis_Santos,customers_Mahnaz_Qafari,customers_Mahsa_Bafrani,customers_Majid_Rafiei,customers_Marco_Pegoraro,customers_Mohammadreza_Fani_Sani,customers_Seran_Uysal,customers_Tobias_Brockhoff,customers_Wil_van_der_Aalst
0,1,2019-05-20 09:07:47,place order,['990001'],NaN,"['880001', '880004', '880003', '880002']",3.520,524.96,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,2,2019-05-20 10:35:21,place order,['990002'],NaN,"['880008', '880005', '880006', '880007']",2.656,3255.99,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,3,2019-05-20 10:38:17,pick item,['990002'],NaN,['880006'],0.483,79.99,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,4,2019-05-20 11:13:54,confirm order,['990001'],NaN,"['880001', '880004', '880003', '880002']",3.520,524.96,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,5,2019-05-20 11:20:13,pick item,['990001'],NaN,['880002'],0.280,89.99,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22362,22363,2020-08-18 11:11:09,send package,['991976'],['661324'],"['888072', '888071']",0.606,1275.00,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
22363,22364,2020-08-19 17:57:32,package delivered,['991976'],['661324'],"['888072', '888071']",0.606,1275.00,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
22364,22365,2020-08-22 01:00:00,create package,['991983'],['661325'],['888091'],0.172,699.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
22365,22366,2020-08-24 11:14:47,send package,['991983'],['661325'],['888091'],0.172,699.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
22366,22367,2020-08-25 16:30:41,package delivered,['991983'],['661325'],['888091'],0.172,699.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [10]:
directory = 'data-prepro'
filename = directory + '/ds2_prepro.csv'

if not os.path.exists(directory):
    os.makedirs(directory)

ds2.to_csv(filename, index=False)

# DS3

In [13]:
ds3 = pd.read_csv('OCEL/angular_github_commits_ocel.csv', sep=',')
with pd.option_context('display.max_columns', None): 
    display(ds3)
ds3['ocel:timestamp'] = pd.to_datetime(ds3['ocel:timestamp'], errors='coerce')
ds3 = ds3.dropna(subset=['ocel:timestamp'])

,ocel:eid,merge,Unnamed: 10,Unnamed: 0,ocel:activity,Unnamed: 11,author_name,commit_message,ocel:timestamp,ocel:type:branches,ocel:type:files
0,6a3abf2366e2c32ce3460155903262fee01736c8,False,NaN,0,initial,NaN,Miško Hevery,Initial commit,2014-09-18 09:12:01-07:00,"['devtools-injector-debugging', 'aikidave-patc...","['.gitignore', 'LICENSE']"
1,afa761646472120edef1f9b01f219f125f20128e,False,NaN,1,build,NaN,Tobias Bosch,build - refactor,2014-09-18 14:56:38-07:00,"['devtools-injector-debugging', 'aikidave-patc...",NaN
2,45f8a5119488d28bf90311b2dd7fc55ee6f7d92a,False,NaN,6,build,NaN,Tobias Bosch,build: prevent infinite loop during install,2014-09-19 14:29:20-07:00,"['devtools-injector-debugging', 'aikidave-patc...",['gulpfile.js']
3,5af57922dbf5b3cf76adb5e3831f9aa21dddc17c,False,NaN,2,chore,NaN,Misko Hevery,chore: add .c9 to gitignore,2014-09-19 21:55:04+00:00,"['devtools-injector-debugging', 'aikidave-patc...",['.gitignore']
4,9f1db3f2bcf67f49c9b145e1d1e8f090220372df,False,NaN,3,chore,NaN,Misko Hevery,chore: correct postinstall.sh script,2014-09-19 21:55:37+00:00,"['devtools-injector-debugging', 'aikidave-patc...","['package.json', 'postinstall.sh']"
...,...,...,...,...,...,...,...,...,...,...,...
27842,8cd9663a9255e4f8dbddb0a888ea21da82082358,False,NaN,27829,release,NaN,Jessica Janiuk,release: cut the v17.0.0-next.3 release,2023-09-06 18:23:35+00:00,"['main', 'g3', 'migrate-saucelabs-to-ga']","['CHANGELOG.md', 'package.json']"
27843,eb0137de8ad498cf37ac238bdd472c8eab542a4d,False,NaN,27840,build,NaN,JoostK,build: migrate `project_id` option to use `bes...,2023-09-07 22:02:21+02:00,"['main', 'g3']",['.bazelrc']
27844,b3edcda9e600297441b5a55406f6b8a217826921,False,NaN,27841,build,NaN,Kristiyan Kostadinov,build: attempt to deflake windows tests (#5170...,2023-09-08 09:13:15+02:00,"['main', 'g3']",['packages/compiler-cli/src/ngtsc/file_system/...
27845,e866d85e95a5974252e5a5bd79281cc33b3b1489,False,NaN,27843,docs,NaN,Alan Agius,docs: typo in what is angular (#51703)\n\nFix ...,2023-09-08 11:23:07+00:00,"['main', 'g3']",['aio/content/guide/what-is-angular.md']
27846,00bf05251b8fe687084fd2871210944ff750e30d,False,NaN,27842,docs,NaN,Angular Robot,docs: update Angular CLI help [main] (#51704)\...,2023-09-08 15:31:45+00:00,"['main', 'g3']","['aio/content/cli/help/build-info.json', 'aio/..."

/tmp/ipykernel_3073/2770231310.py:4: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  ds3['ocel:timestamp'] = pd.to_datetime(ds3['ocel:timestamp'], errors='coerce')

In [14]:
ds3 = ds3.drop(columns=["Unnamed: 10","Unnamed: 0","Unnamed: 11","commit_message"])
ds3.columns = ds3.columns.str.replace('ocel:', '')
ds3.columns = ds3.columns.str.replace('type:', '')
ds3 = ds3.rename(columns={'timestamp': 'event_timestamp', 'activity': 'event_activity', "eid": "event_id"})
ds3['event_id'] = range(len(ds3))
display(ds3)

,event_id,merge,event_activity,author_name,event_timestamp,branches,files
0,0,False,initial,Miško Hevery,2014-09-18 09:12:01-07:00,"['devtools-injector-debugging', 'aikidave-patc...","['.gitignore', 'LICENSE']"
1,1,False,build,Tobias Bosch,2014-09-18 14:56:38-07:00,"['devtools-injector-debugging', 'aikidave-patc...",NaN
2,2,False,build,Tobias Bosch,2014-09-19 14:29:20-07:00,"['devtools-injector-debugging', 'aikidave-patc...",['gulpfile.js']
3,3,False,chore,Misko Hevery,2014-09-19 21:55:04+00:00,"['devtools-injector-debugging', 'aikidave-patc...",['.gitignore']
4,4,False,chore,Misko Hevery,2014-09-19 21:55:37+00:00,"['devtools-injector-debugging', 'aikidave-patc...","['package.json', 'postinstall.sh']"
...,...,...,...,...,...,...,...
27842,27842,False,release,Jessica Janiuk,2023-09-06 18:23:35+00:00,"['main', 'g3', 'migrate-saucelabs-to-ga']","['CHANGELOG.md', 'package.json']"
27843,27843,False,build,JoostK,2023-09-07 22:02:21+02:00,"['main', 'g3']",['.bazelrc']
27844,27844,False,build,Kristiyan Kostadinov,2023-09-08 09:13:15+02:00,"['main', 'g3']",['packages/compiler-cli/src/ngtsc/file_system/...
27845,27845,False,docs,Alan Agius,2023-09-08 11:23:07+00:00,"['main', 'g3']",['aio/content/guide/what-is-angular.md']
27846,27846,False,docs,Angular Robot,2023-09-08 15:31:45+00:00,"['main', 'g3']","['aio/content/cli/help/build-info.json', 'aio/..."

In [15]:
objects = ['branches', 'files']
first_cols = ['event_id', 'event_timestamp', 'event_activity'] + objects
split = []
ds3 = preprocess_dataframe(ds3, first_cols, split)
ds3['event_timestamp'] = pd.to_datetime(ds3['event_timestamp'], errors='coerce', utc=True)
ds3['event_timestamp'] = ds3['event_timestamp'].dt.tz_localize(None)
ds3['event_timestamp'] = ds3['event_timestamp'].dt.strftime('%Y/%m/%d %H:%M:%S')
display(ds3)

,event_id,event_timestamp,event_activity,branches,files,author_name_ add more tests,author_name_ add overflow to tree wrapper,author_name_ add test,author_name_ always include nativeElement in buildDirectiveForest,author_name_ apply styling to expansion header,...,author_name_雪狼,author_name_nan,merge_AleksanderBodurri,merge_False,merge_True,merge_alex.bodurri@mail.utoronto.ca,merge_misko@hevery.com,merge_victor@suumit.com,merge_wardbell@hotmail.com,merge_yjbanov@google.com
0,0,2014/09/18 16:12:01,initial,"['devtools-injector-debugging', 'aikidave-patc...","['.gitignore', 'LICENSE']",False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,1,2014/09/18 21:56:38,build,"['devtools-injector-debugging', 'aikidave-patc...",NaN,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,2,2014/09/19 21:29:20,build,"['devtools-injector-debugging', 'aikidave-patc...",['gulpfile.js'],False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,3,2014/09/19 21:55:04,chore,"['devtools-injector-debugging', 'aikidave-patc...",['.gitignore'],False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,4,2014/09/19 21:55:37,chore,"['devtools-injector-debugging', 'aikidave-patc...","['package.json', 'postinstall.sh']",False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27842,27842,2023/09/06 18:23:35,release,"['main', 'g3', 'migrate-saucelabs-to-ga']","['CHANGELOG.md', 'package.json']",False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27843,27843,2023/09/07 20:02:21,build,"['main', 'g3']",['.bazelrc'],False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27844,27844,2023/09/08 07:13:15,build,"['main', 'g3']",['packages/compiler-cli/src/ngtsc/file_system/...,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27845,27845,2023/09/08 11:23:07,docs,"['main', 'g3']",['aio/content/guide/what-is-angular.md'],False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27846,27846,2023/09/08 15:31:45,docs,"['main', 'g3']","['aio/content/cli/help/build-info.json', 'aio/...",False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [16]:
directory = 'data-prepro'
filename = directory + '/ds3_prepro.csv'

if not os.path.exists(directory):
    os.makedirs(directory)

ds3.to_csv(filename, index=False)

# DS4

In [25]:
ds4 = pd.read_csv('OCEL/windows_events.csv', sep=',')
with pd.option_context('display.max_columns', None): 
    display(ds4)
ds4.columns = ds4.columns.str.replace('ocel:', '')
ds4.columns = ds4.columns.str.replace('type:', '')
ds4 = ds4.rename(columns={'timestamp': 'event_timestamp', 'activity': 'event_activity', "eid": "event_id"})
display(ds4)

,ocel:eid,ocel:timestamp,ocel:activity,ocel:type:categoryString,ocel:type:computerName,ocel:type:eventIdentifier,ocel:type:eventType,ocel:type:sourceName,ocel:type:user
0,0,2021-01-10 11:36:17.932273,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
1,1,2021-01-10 11:37:15.331308,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
2,2,2021-01-10 11:37:16.468248,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
3,3,2021-01-10 11:54:57.216991,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
4,4,2021-01-12 05:05:40.261808,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
...,...,...,...,...,...,...,...,...,...
98123,98123,2022-11-09 11:38:18.838244,Microsoft-Windows-RestartManager 10001,['None'],['DESKTOP-JF7J584'],['10001'],['3'],['Microsoft-Windows-RestartManager'],['DESKTOP-JF7J584\\berti']
98124,98124,2022-11-09 11:43:20.767319,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
98125,98125,2022-11-09 12:03:31.515357,Firefox Default Browser Agent 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['Firefox Default Browser Agent'],NaN
98126,98126,2022-11-09 12:03:31.516356,Firefox Default Browser Agent 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['Firefox Default Browser Agent'],NaN
98127,98127,2022-11-09 12:13:26.086808,gupdate 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['gupdate'],NaN

,event_id,event_timestamp,event_activity,categoryString,computerName,eventIdentifier,eventType,sourceName,user
0,0,2021-01-10 11:36:17.932273,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
1,1,2021-01-10 11:37:15.331308,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
2,2,2021-01-10 11:37:16.468248,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
3,3,2021-01-10 11:54:57.216991,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
4,4,2021-01-12 05:05:40.261808,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
...,...,...,...,...,...,...,...,...,...
98123,98123,2022-11-09 11:38:18.838244,Microsoft-Windows-RestartManager 10001,['None'],['DESKTOP-JF7J584'],['10001'],['3'],['Microsoft-Windows-RestartManager'],['DESKTOP-JF7J584\\berti']
98124,98124,2022-11-09 11:43:20.767319,Microsoft Office 16 Alerts 300,['None'],['DESKTOP-JF7J584'],['300'],['3'],['Microsoft Office 16 Alerts'],NaN
98125,98125,2022-11-09 12:03:31.515357,Firefox Default Browser Agent 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['Firefox Default Browser Agent'],NaN
98126,98126,2022-11-09 12:03:31.516356,Firefox Default Browser Agent 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['Firefox Default Browser Agent'],NaN
98127,98127,2022-11-09 12:13:26.086808,gupdate 0,['None'],['DESKTOP-JF7J584'],NaN,"['0', '3']",['gupdate'],NaN

In [26]:
objects = ['categoryString', 'computerName', 'eventIdentifier',"eventType","sourceName"]
first_cols = ['event_id', 'event_timestamp', 'event_activity'] + objects
split = ["user"]
ds4 = preprocess_dataframe(ds4, first_cols, split)
# display(ds4)

In [27]:
directory = 'data-prepro'
filename = directory + '/ds4_prepro.csv'

if not os.path.exists(directory):
    os.makedirs(directory)

ds4.to_csv(filename, index=False)

In [29]:
ds4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98128 entries, 0 to 98127
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   event_id                            98128 non-null  int64
 1   event_timestamp                     98128 non-null  object
 2   event_activity                      98128 non-null  object
 3   categoryString                      98128 non-null  object
 4   computerName                        98128 non-null  object
 5   eventIdentifier                     94495 non-null  object
 6   eventType                           98128 non-null  object
 7   sourceName                          98128 non-null  object
 8   user_DESKTOP-JF7J584\\berti         98128 non-null  float64
 9   user_NT_AUTHORITY\\LOCAL_SERVICE    98128 non-null  float64
 10  user_NT_AUTHORITY\\NETWORK_SERVICE  98128 non-null  float64
 11  user_NT_AUTHORITY\\SYSTEM           98128 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 9.0+ MB